# Custom Language File for Launcher Customizer

[ejs.app]
title = "PinkyCore Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Luca-Caporaloni/PinkyCoreLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/TBVbbQuPbr"

[ejs.settings]
sourceGithubLink = "https://github.com/Luca-Caporaloni/PinkyCoreLauncher"
supportLink = "https://github.com/Luca-Caporaloni/PinkyCoreLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO PINKYCORE"
welcomeDescription = "We wish you a good time!"
welcomeDescCTA = ""
